services:
  kurikone-cb-bot:
    image: ghcr.io/kurisutaru/kurikone-cb-bot
    container_name: kurikone-cb-bot
    network_mode: bridge
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped